from datetime import datetime

from pydantic import BaseModel, Field


class Alert(BaseModel):
    """Represent a security alert generated by Extension AI Guard."""

    alert_id: str = Field(
        ...,
        description="Unique identifier for the alert",
    )
    result_id: str = Field(
        ...,
        description="Identifier of the detection result that generated the alert",
    )
    severity: str = Field(
        ...,
        pattern="^(low|medium|high|critical)$",
        description="Alert severity level",
    )
    title: str = Field(
        ...,
        description="Short title of the security alert",
    )
    message: str = Field(
        ...,
        description="Detailed alert message",
    )
    created_at: datetime = Field(
        ...,
        description="Time when the alert was created",
    )
    acknowledged: bool = Field(
        default=False,
        description="Whether the alert has been acknowledged",
    )