def get_aegis_welcome() -> dict:
    """Return the initial Aegis welcome message."""
    return {
        "assistant": "Aegis",
        "message": (
            "Welcome to Extension AI Guard. "
            "I am Aegis, your security assistant."
        ),
    }


def get_aegis_response(message: str) -> dict:
    """Return a deterministic Aegis response based on the user's message."""
    normalized_message = message.strip().lower()

    if not normalized_message:
        return {
            "assistant": "Aegis",
            "message": "Please enter a security-related question or message.",
        }

    if "what is extension ai guard" in normalized_message:
        response = (
            "Extension AI Guard is a security platform designed to analyze "
            "browser extension network traffic and identify suspicious behavior."
        )
    elif "network traffic" in normalized_message:
        response = (
            "Network traffic analysis examines the requests, destinations, "
            "methods, headers, and other communication patterns generated by "
            "a browser extension."
        )
    elif "malicious extension" in normalized_message:
        response = (
            "A malicious browser extension is an extension that performs "
            "harmful or unauthorized actions, such as stealing sensitive data, "
            "communicating with suspicious destinations, or abusing browser permissions."
        )
    elif "how does aegis detect" in normalized_message:
        response = (
            "Aegis currently provides deterministic security guidance. "
            "The project's detection engine will analyze extension traffic "
            "and security events, which Aegis can later explain to users."
        )
    else:
        response = (
            "I am Aegis, the Extension AI Guard security assistant. "
            "I can help explain browser extension security, network traffic "
            "analysis, suspicious behavior, and safe security testing."
        )

    return {
        "assistant": "Aegis",
        "message": response,
    }

def get_aegis_knowledge() -> dict:
    """Return the security topics currently supported by Aegis."""
    return {
        "assistant": "Aegis",
        "topics": [
            {
                "id": "extension-security",
                "name": "Browser Extension Security",
                "description": (
                    "Understand browser extension security risks, "
                    "permissions, and common attack behaviors."
                ),
            },
            {
                "id": "network-traffic",
                "name": "Network Traffic Analysis",
                "description": (
                    "Learn how extension network requests and communication "
                    "patterns can be analyzed for suspicious behavior."
                ),
            },
            {
                "id": "malicious-extensions",
                "name": "Malicious Extension Behavior",
                "description": (
                    "Understand how malicious extensions can abuse permissions, "
                    "access sensitive data, or communicate with suspicious destinations."
                ),
            },
            {
                "id": "safe-testing",
                "name": "Safe Security Testing",
                "description": (
                    "Learn how to perform controlled and isolated security "
                    "testing without targeting real users or systems."
                ),
            },
            {
                "id": "detection-alerts",
                "name": "Detection and Security Alerts",
                "description": (
                    "Understand how suspicious traffic can become security "
                    "events and alerts for further investigation."
                ),
            },
        ],
    }
def explain_aegis_alert(
    severity: str,
    title: str,
    message: str,
) -> dict:
    """Return a deterministic human-readable explanation for a security alert."""
    normalized_severity = severity.strip().lower()

    if normalized_severity == "critical":
        action = (
            "Immediately isolate the affected extension and investigate "
            "the associated network activity."
        )
    elif normalized_severity == "high":
        action = (
            "Investigate the affected extension and review its network "
            "activity before continuing normal use."
        )
    elif normalized_severity == "medium":
        action = (
            "Review the alert details and monitor the extension for "
            "additional suspicious behavior."
        )
    else:
        action = (
            "Review the alert and continue monitoring the extension "
            "for unusual activity."
        )

    return {
        "assistant": "Aegis",
        "severity": normalized_severity,
        "title": title,
        "alert": message,
        "explanation": (
            f"This alert has a {normalized_severity} severity level. "
            f"The alert '{title}' indicates the following security concern: "
            f"{message}"
        ),
        "recommended_action": action,
    }